image: php:5.6.31

pipelines:
    branches:
        master:
            - step:
                name: Setup, build, and deploy
                caches:
                    - composer
                script:
                    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
                    - apt-get update && apt-get install -y zip unzip ca-certificates bash git nodejs
                    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
                    - composer global require "banago/phploy"
                    - npm install
                    - npm run build
                    - ln -s /root/.composer/vendor/banago/phploy/bin/phploy /usr/local/bin/phploy
                    - phploy -l
