image: php:5.6.31

pipelines:
    branches:
        master:
            caches:
                - composer
            - step:
                name: Build and deploy
                script:
                    - apt-get update && apt-get install -y zip unzip ca-certificates bash git nodejs
                    - npm install
                    - npm run build
                    - ls -la
                    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
                    - composer global require "banago/phploy"
                    - ln -s /root/.composer/vendor/banago/phploy/bin/phploy /usr/local/bin/phploy
                    - phploy -l
