image: php:5.6.31

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y ca-certificates bash git
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - git clone --depth 1 https://github.com/banago/PHPloy.git && mv PHPloy/bin/phploy /usr/bin/phploy && rm -rf PHPloy
          - phploy -l
